import { computed, inject, LOCALE_ID, type Signal } from '@angular/core';
import {
  type CreateFormControlOptions,
  type DerivedSignal,
  formControl,
  FormControlSignal,
} from '@mmstack/form-core';
import {
  type DateValidatorOptions,
  injectValidators,
} from '@mmstack/form-validation';

/**
 * Represents the reactive state for a date input form control.
 *
 * Extends the base `FormControlSignal<TDate | null>` and adds date-specific
 * properties like `placeholder` and enhanced `error`/`errorTooltip` signals derived
 * from the validation result's `.resolve()` method (when using the injected factory).
 *
 * @template TParent The type of the parent form group's value, if applicable. Defaults to `undefined`.
 * @template TDate The type used for date values within the control (e.g., `Date`, Luxon `DateTime`, Moment). Defaults to `Date`.
 * @see FormControlSignal
 */
export type DateState<TParent = undefined, TDate = Date> = FormControlSignal<
  TDate | null, // Value can be the specific date type or null
  TParent
> & {
  /** Signal holding the input placeholder text (e.g., "YYYY-MM-DD"). */
  placeholder: Signal<string>;
  /**
   * Signal holding the formatted error message suitable for tooltips or detailed display.
   * When multiple validation errors occur, this may contain all messages, while `error()` might show a summary.
   * (Generated by `injectCreateDateState` using the validator's `.resolve()` method).
   */
  errorTooltip: Signal<string>;
  /**
   * Signal holding the minimum selectable date (inclusive), derived from options.
   * Returns `null` if no minimum date is set. The value is always a `Date` object internally
   * for reliable comparison, regardless of the input option format (`string` or `Date`).
   * Useful for binding to date picker component properties (e.g., `[min]`).
   */
  min: Signal<Date | null>;
  /**
   * Signal holding the maximum selectable date (inclusive), derived from options.
   * Returns `null` if no maximum date is set. The value is always a `Date` object internally.
   * Useful for binding to date picker component properties (e.g., `[max]`).
   */
  max: Signal<Date | null>;
  /** Type discriminator for date controls. */
  type: 'date';
};

/**
 * Configuration options for the `createDateState` function (the non-DI version).
 * Extends base form control options for a `TDate | null` value.
 *
 * @template TDate The type used for date values. Defaults to `Date`.
 * @see CreateFormControlOptions
 * @see createDateState
 */
export type DateStateOptions<TDate = Date> = CreateFormControlOptions<
  TDate | null,
  'control'
> & {
  /**
   * The locale string (e.g., 'en-US', 'de-DE'). While required by this type,
   * it's primarily intended to be passed down internally when using the
   * dependency-injected factory (`injectCreateDateState`) which obtains it from `LOCALE_ID`.
   * If using `createDateState` directly, you must provide it manually, but its primary
   * use is within the validation message formatting handled by the injected system.
   */
  locale: string;
  /** Optional function returning the placeholder text for the date input. */
  placeholder?: () => string;
  /**
   * Optional function returning the minimum selectable date (inclusive).
   * Accepts a string (parsed as `new Date(string)`), a `Date` object, or `null`.
   * Populates the `min` signal on the `DateState`.
   * Note: If using `injectCreateDateState`, setting `min` via the `validation`
   * options is generally preferred as it enables validation messages.
   */
  min?: () => string | Date | null;
  /**
   * Optional function returning the maximum selectable date (inclusive).
   * Accepts a string (parsed as `new Date(string)`), a `Date` object, or `null`.
   * Populates the `max` signal on the `DateState`.
   * Note: If using `injectCreateDateState`, setting `max` via the `validation`
   * options is generally preferred as it enables validation messages.
   */
  max?: () => string | Date | null;
};

/**
 * Configuration options specifically for the factory function returned by
 * `injectCreateDateState`.
 *
 * This type omits base properties handled internally by the factory (like `validator`, `required`, `locale`)
 * and requires validation rules to be provided via the `validation` property using `DateValidatorOptions`
 * from `@mmstack/form-validation`.
 *
 * @template TDate The type used for date values. Defaults to `Date`.
 * @see injectCreateDateState
 * @see DateStateOptions
 * @see DateValidatorOptions
 */
export type InjectedDateStateOptions<TDate = Date> = Omit<
  // Options related to validation rules or locale are handled internally
  DateStateOptions<TDate>,
  'required' | 'validator' | 'locale' | 'min' | 'max'
> & {
  /**
   * Optional function returning a `DateValidatorOptions` object defining the validation rules.
   * The `min`, `max` & `required` properties set here will be used for both validation *and* to populate
   * the `min`, `max` & `required` signals on the resulting `DateState`.
   * The factory function uses this configuration with the injected `validators.date.all()` method.
   *
   * @example validation: () => ({ required: true, min: new Date(), max: '2099-12-31' })
   */
  validation?: () => DateValidatorOptions;
};

/**
 * Creates the reactive state object (`DateState`) for a date form control
 * without relying on Angular's dependency injection for validation or locale.
 * Includes computed signals for `min` and `max` date constraints based directly on the provided options.
 *
 * Use this function directly only if creating state outside an injection context
 * or providing a fully custom `validator`, `locale`, `min`, and `max` manually via `opt`.
 * Prefer `injectCreateDateState` for standard usage within Angular applications.
 *
 * Note: The `errorTooltip` signal returned by this function will initially be empty.
 * Enhanced tooltip generation based on multiple errors is handled by `injectCreateDateState`.
 *
 * @template TParent The type of the parent form group's value, if applicable. Defaults to `undefined`.
 * @template TDate The type used for date values. Defaults to `Date`.
 * @param value The initial date value (`TDate | null`), or a `DerivedSignal` linking it to a parent state.
 * @param opt Configuration options (`DateStateOptions`), requires `locale`, optionally `validator`, `placeholder`, `min`, `max`.
 * @returns A `DateState` instance managing the control's reactive state, including `min` and `max` signals.
 * @see injectCreateDateState
 */
export function createDateState<TParent = undefined, TDate = Date>(
  value: TDate | null | DerivedSignal<TParent, TDate | null>,
  opt: DateStateOptions<TDate>,
): DateState<TParent, TDate> {
  const state = formControl<TDate | null, TParent>(value, opt);

  return {
    ...state,
    min: computed(
      () => {
        const min = opt.min?.();
        if (!min) return null;
        return typeof min === 'string' ? new Date(min) : min;
      },
      {
        equal: (a, b) => a?.getTime() === b?.getTime(),
      },
    ),
    max: computed(() => {
      const max = opt.max?.();
      if (!max) return null;
      return typeof max === 'string' ? new Date(max) : max;
    }),
    placeholder: computed(() => opt.placeholder?.() ?? ''),
    errorTooltip: computed(() => ''),
    type: 'date',
  };
}

/**
 * Creates and returns a factory function for generating `DateState` instances.
 *
 * This factory utilizes Angular's dependency injection (`injectValidators`, `LOCALE_ID`)
 * to automatically handle:
 * - Validation configuration via `DateValidatorOptions` (passed to the `validation` option).
 * - Localization for default validation error messages.
 * - Enhanced error message formatting (splitting merged errors into `error` and `errorTooltip` signals).
 * - Populating the `min` and `max` signals on `DateState` based on the constraints specified
 * within the `validation` options object.
 * - Configuration of date handling based on `provideValidatorConfig`.
 *
 * This is the **recommended** way to create `DateState` within an Angular application.
 *
 * @returns A factory function: `(value: TDate | null | DerivedSignal<TParent, TDate | null>, opt?: InjectedDateStateOptions<TDate>) => DateState<TParent, TDate>`.
 * @template TDate The type used for date values passed to the factory (e.g., `Date`, Luxon `DateTime`).
 * Must match the `TDate` used during `provideValidatorConfig` if custom date handling is required. Defaults to `Date`.
 *
 * @example
 * // Within an injection context:
 * const createDate = injectCreateDateState();
 * // If using Luxon: const createDate = injectCreateDateState<DateTime>();
 *
 * const eventDateState = createDate(null, {
 * label: () => 'Event Date',
 * placeholder: () => 'Select event date',
 * validation: () => ({ // Provide DateValidatorOptions here
 * required: true,
 * min: new Date(), // Sets min validation AND state.min() signal
 * max: '2099-12-31'  // Sets max validation AND state.max() signal
 * })
 * });
 *
 * // Template can use min/max signals for datepicker limits:
 * // <mat-datepicker-toggle [for]="picker" [disabled]="eventDateState.disabled()"></mat-datepicker-toggle>
 * // <input matInput [matDatepicker]="picker"
 * //        [min]="eventDateState.min()"
 * //        [max]="eventDateState.max()"
 * //        [(ngModel)]="eventDateState.value" ... >
 * // <mat-datepicker #picker></mat-datepicker>
 * // <mat-error><span [matTooltip]="eventDateState.errorTooltip()">{{ eventDateState.error() }}</span></mat-error>
 */
export function injectCreateDateState() {
  const validators = injectValidators();
  const locale = inject(LOCALE_ID);

  /**
   * Factory function (returned by `injectCreateDateState`) that creates `DateState`.
   * Integrates with `@mmstack/form-validation` via DI for validation and localization.
   * Handles splitting of multiple validation errors into `error` and `errorTooltip`.
   * Derives `min`/`max` state signals from `validation` options.
   *
   * @template TDate The type for date values used by this control. Defaults to `Date`.
   * @template TParent The type of the parent form group's value, if applicable. Defaults to `undefined`.
   * @param value The initial date value (`TDate | null`), or a `DerivedSignal` linking it to a parent state.
   * @param opt Configuration options (`InjectedDateStateOptions`), including the `validation` property
   * which accepts `DateValidatorOptions` (used for both validation rules and setting state's `min`/`max` signals).
   * @returns A `DateState` instance managing the control's reactive state.
   */
  return <TDate = Date, TParent = undefined>(
    value: TDate | null | DerivedSignal<TParent, TDate | null>,
    opt?: InjectedDateStateOptions<TDate>,
  ) => {
    const validationOptions = computed(() => ({
      messageOptions: {
        label: opt?.label?.(),
      },
      ...opt?.validation?.(),
    }));

    const mergedValidator = computed(() =>
      validators.date.all(validationOptions()),
    );

    const validator = computed(() => {
      const merged = mergedValidator();

      return (value: TDate | null) => {
        return merged(value as Date);
      };
    });

    const state = createDateState(value, {
      ...opt,
      locale,
      min: computed(() => validationOptions().min ?? null),
      max: computed(() => validationOptions().max ?? null),
      required: computed(() => validationOptions().required ?? false),
      validator,
    });

    const resolvedError = computed(() => {
      const merger = mergedValidator();

      return merger.resolve(state.error());
    });

    return {
      ...state,
      error: computed(() => resolvedError().error),
      errorTooltip: computed(() => resolvedError().tooltip),
    };
  };
}
